name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1tTXNwnjmnDUY7h8VYGWMWQZCcP_7mP3rK7u7Ew1oQ4E27Jth
        USER_PASS: xiaohaha
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h
